const books = [
  {
    id: 1,
    title: "Harry Potter",
    author: "J. K. Rowling",
    year: 1967,
    isAvailable: false,
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    isAvailable: false,
  },
  {
    id: 3,
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    year: 1937,
    isAvailable: true,
  },
  {
    id: 4,
    title: "The Lord of the Rings",
    author: "J. R. R. Tolkien",
    year: 1954,
    isAvailable: false,
  },
  {
    id: 5,
    title: "Animal Farm",
    author: "George Orwell",
    year: 1945,
    isAvailable: false,
  },
  {
    id: 6,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: 1953,
    isAvailable: false,
  },
  {
    id: 7,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    isAvailable: false,
  },
  {
    id: 8,
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    year: 1951,
    isAvailable: false,
  },
  {
    id: 9,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    isAvailable: false,
  },
  {
    id: 10,
    title: "Moby Dick",
    author: "Herman Melville",
    year: 1851,
    isAvailable: false,
  },

  {
    id: 11,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    isAvailable: false,
  },
  {
    id: 12,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    isAvailable: false,
  },
  {
    id: 13,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    isAvailable: false,
  },
  {
    id: 14,
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    year: 1847,
    isAvailable: false,
  },
  {
    id: 15,
    title: "Wuthering Heights",
    author: "Emily Bronte",
    year: 1847,
    isAvailable: false,
  },
  {
    id: 16,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    isAvailable: false,
  },
  {
    id: 17,
    title: "The Odyssey",
    author: "Homer",
    year: -700,
    isAvailable: false,
  },
  {
    id: 18,
    title: "The Iliad",
    author: "Homer",
    year: -750,
    isAvailable: false,
  },
  {
    id: 19,
    title: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    isAvailable: true,
  },
  {
    id: 20,
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    isAvailable: true,
  },

  {
    id: 21,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    isAvailable: true,
  },
  {
    id: 22,
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    isAvailable: true,
  },
  {
    id: 23,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    year: 1605,
    isAvailable: true,
  },
  {
    id: 24,
    title: "The Little Prince",
    author: "Antoine de Saint-Exupery",
    year: 1943,
    isAvailable: true,
  },
  {
    id: 25,
    title: "The Chronicles of Narnia",
    author: "C. S. Lewis",
    year: 1950,
    isAvailable: true,
  },
  {
    id: 26,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    year: 2003,
    isAvailable: true,
  },
  {
    id: 27,
    title: "Angels and Demons",
    author: "Dan Brown",
    year: 2000,
    isAvailable: true,
  },
  {
    id: 28,
    title: "The Shining",
    author: "Stephen King",
    year: 1977,
    isAvailable: true,
  },
  {
    id: 29,
    title: "It",
    author: "Stephen King",
    year: 1986,
    isAvailable: true,
  },
  {
    id: 30,
    title: "Dune",
    author: "Frank Herbert",
    year: 1965,
    isAvailable: true,
  },
];

export default books;
